### ISSUE TITLE
"close" is written to stderr

### ISSUE THREAD

**Issue by regular** [dominictarr/stream-to-pull-stream#7]
Hi Dominic,

I am having a lot of fun playing with pull-streams. To parse JSON, I m wrapping JSONStream into stream-to-pull-stream, which seems to work fine. However, I am a bit irritated by [this line](https://github.com/dominictarr/stream-to-pull-stream/blob/bb17eab01bd648c03f96ac41d1d9f604f5e44faf/index.js#L29)

Is that debug output that was left here by accident (I guess it is), or does it actually indicate that something did not went as smoothly as it should have?

Thanks for the great module eco-system that pull-streams are!

**Comment by dominictarr** [comment]
thanks, yes I noticed that yesterday, but hadn't gotten around to fixing it yet.
Fixed now! I am glad you like pull-streams! cheers!

**Comment by dominictarr** [comment]
(fixed in 1.6.6)

**Comment by regular** [comment]
Great, thank you!
